### ISSUE TITLE
build prerequisites should be declared as 'test' [rt.cpan.org #106724]

### ISSUE THREAD

**Issue by stsc** [stsc/DateTime-Format-Natural#10]
Migrated from [rt.cpan.org#106724](https://rt.cpan.org/Ticket/Display.html?id=106724) (status was 'new')

Requestors:
* ether@cpan.org

From ether@cpan.org on 2015-08-28 21:40:16
:
```
The prerequisites used by the tests are declared as "build_requires", but they should be "test_requires".
```

**Comment by stsc** [comment]
github #20 by Olaf Alders (merged in `v1.14_02`) declares `Test::MockTime::HiRes` and `Test::More` with `test_requires`.

Is this sufficient? :-).

**Comment by karenetheridge** [comment]
There are still some modules in build_requires that should be moved, e.g. Module::Util.

Also, I would strongly recommend not using Module::Build::Compat, as it produces mismatched Makefile.PL files. You may find Module::Build::Tiny to be easier to use, as it has less twiddly knobs and produces nicer metadata.

**Comment by stsc** [comment]
All testing modules have been moved now (to my knowledge). See #9 for the removal of `Makefile.PL`.

Closing. Feel free to open a new issue as the need arises.
