### ISSUE TITLE
whishlist - allow more values after keywords before and after

### ISSUE THREAD

**Issue by Sadrak** [stsc/DateTime-Format-Natural#17]
I want to allow more combinations with `before` and `after` for my programm to describe a timestamp:

* 5 minutes before next hour
* 10 hours after this minute
* 2 minutes after 2 minutes before now ;)
* 1 minute after 2 minutes after 3 minutes after now

Is this possible? I can add this in our wrapper, but i want to first try a direct support for such a feature.

My solution would be:
* use string after first `before`/`after` in an extra call to parse_datetime()
* use the returned value from the extra call as value for `datetime` argument and replace the extracted string with `now`
* enable recursion

**Comment by stsc** [comment]
- 5 minutes before next hour
- 10 hours after this minute

look good to me, whereas

- 2 minutes after 2 minutes before now
- 1 minute after 2 minutes after 3 minutes after now

admittedly seem a bit freaky ;). And yes, your solution appears to work for those.

I'm a bit reluctant to include latter two and similar ones, but feel free to send example
input based on former pattern of expressions you suggested.

Such changes would require that the grammer is amended and possibly some
calculating worker methods to be added among other things.

**Comment by Sadrak** [comment]
OK, the implementation was that easy (only 9 lines of code) in my wrapper.

One gotcha was that it is `from now` and not `after now` (i am not a native speaker and was confused why one case was not working). Please rate my ~~setup~~ example:

```perl
sub humantime_to_datetime {
    my ($class, $humantime, $basetime, $timezone) = @_;

    if ($humantime =~ /\s(before|after)\s/i) {
        my $relation = $1;
        my ($left, $right) = split($relation, $humantime, 2);
        if ($right !~ /^\s*now\s*$/i) {
            $basetime  = $class->humantime_to_unixtime($right, $basetime, $timezone);
            return if not defined $basetime;
            $humantime = $relation eq 'after' ? "$left from now" : "$left $relation now";
        }
    }

    my $dt_time           = DateTime->from_epoch(epoch => $basetime // time(), time_zone => $timezone // 'UTC');
    my $dt_parser_natural = DateTime::Format::Natural->new(datetime => $dt_time, time_zone => $timezone // 'UTC');

    my $dt = $dt_parser_natural->parse_datetime($humantime);
    return $dt if $dt_parser_natural->success;
    return;
}
```

i know this has some drawbacks (`4 hours before today` is currently direct supported but will run though my code and become `4 hours before now` with datetime option set to the result from `today`), but it works really good in my usecase.

> admittedly seem a bit freaky

I think there is no reason to restrict users. One valid case is using different time units: `5 seconds after 1 minute after next hour` and perhaps many more that would be blocked with a restriction.

OK, what are the next steps?

P.S.:
Perhaps such feature for timespans with the keyword `for` and additonal keyword `and` would be good: `for 5 seconds and 2 minutes`

**Comment by stsc** [comment]
> Please rate my ~setup~ example:
> [code]

Appears appropriate.

> I think there is no reason to restrict users. One valid case is using different time units: `5 seconds after 1 minute after next hour` and perhaps many more that would be blocked with a restriction.

I don't want to restrict users, i just tried to emphasize the uncommonness :-).

> OK, what are the next steps?

If you strive to support "endlessly" chained expressions out-of-the-box, you'd have to alter `parse_datetime()`. Recursively calling `parse_datetime()` as it is mostly now will unfortunately not work. This would require a bit more work. And what i outlined above.

Hope this helps,

**Comment by Sadrak** [comment]
After giving my idea some time for maturing i am not sure if this feature is as good/needed as i thought in the beginning. Sure, there are use cases, but is it worth to be implemented?

Perhaps i will keep my workaround and if this get adapted from my users, i can think about direct support :thinking:

**Comment by stsc** [comment]
You're welcome.

Closing (feel free to open an issue whenever need arises).
