### ISSUE TITLE
Please add support for milliseconds (nanoseconds?)

### ISSUE THREAD

**Issue by Sadrak** [stsc/DateTime-Format-Natural#18]
I would love to get more exact timestamps from this module.

`600 milliseconds before 15:00` would be cool for my users to define the exact moment to execute stuff.

**Comment by Sadrak** [comment]
Or `14:59:59.400`

**Comment by stsc** [comment]
This sounds reasonable.

I plan on implementing the millisecond use case, because I'm tempted to believe this will be the more common one :-).

Please check the attached patch if it goes in the right direction for you!

[dtfn.patch.txt](https://github.com/stsc/DateTime-Format-Natural/files/9035083/dtfn.patch.txt)

**Comment by Sadrak** [comment]
Sorry, i played with the patch but can't get proper results.

But i guess the user requirement is straight forward and most of the implementation could be copied.

> I plan on implementing the millisecond use case, because I'm tempted to believe this will be the more common one :-).

why not both? [meme image]

**Comment by stsc** [comment]
> Sorry, i played with the patch but can't get proper results.

It just "implements" `last millisecond`. Or, did you test something different?

> > I plan on implementing the millisecond use case, because I'm tempted to believe this will be the more common one :-).
> 
> why not both? [meme image]

Requires effort. And i wish I had more time. Consider [sponsoring me](http://refcnt.org/~sts/#sponsorship) :-).

**Comment by Sadrak** [comment]
i tried `last millisecond` (that was the part i understand from the patch), but `parse_datetime()` returned `undef`. I am not very familiar with `patch`, perhaps there was the problem :thinking: 

> And i wish I had more time.

i know exactly what you mean.

> Consider [sponsoring me](http://refcnt.org/~sts/#sponsorship) :-)

I will contact you via mail.

**Comment by stsc** [comment]
> i tried `last millisecond` (that was the part i understand from the patch), but `parse_datetime()` returned `undef`. I am not very familiar with `patch`, perhaps there was the problem

Works here:
`[sts@apollo ~/dev/DateTime-Format-Natural]$ perl -Ilib -MDateTime::Format::Natural -le 'print DateTime::Format::Natural->new->parse_datetime("last millisecond")->strftime("%N")'`
`999000000`

Try this in the clean DTFN source directory:
`patch -p1 < dtfn.patch`

Best luck,

**Comment by stsc** [comment]
**Update:**
I added according millisecond entries to the grammar class whenever it contained a 'second' case.
Please patch your DTFN copy, validate the new entries using `dateparse` and let me know!

Work in progress :-).

**Comment by stsc** [comment]
Whoops, patch missing:
[dtfn.patch.txt](https://github.com/stsc/DateTime-Format-Natural/files/9074836/dtfn.patch.txt)

**Comment by stsc** [comment]
Just a gentle reminder in case it slipped through...

**Comment by stsc** [comment]
Uploaded `v1.13_01` which includes support for millisecond(s).

Let me know, if it works for you!

Best,

**Comment by stsc** [comment]
Support for millisecond(s) now available in stable `v1.14`.

Closing.
