### ISSUE TITLE
parse_datetime failure

### ISSUE THREAD

**Issue by nigelhorne** [stsc/DateTime-Format-Natural#4]
Sometimes I get this message from parse_datetime('16-Dec-2018')

 Undefined subroutine &DateTime::Format::Natural::Compat::check_date called

I've checked your documentation and Google and can't find why that would occur.

**Comment by stsc** [comment]
Compat.pm imports check_date() from Date::Calc. Not sure why that should fail, though.
What Date::Calc version were you using?

**Comment by nigelhorne** [comment]
I am using Date::Calc version 6.4.

**Comment by stsc** [comment]
Ran `$parser->parse_datetime("16-Dec-2018")` 1000 times with Date::Calc 6.4 and latest DT:F:N v1.06. Cannot reproduce here.
