### ISSUE TITLE
Wishlist: add quarter as a keyword

### ISSUE THREAD

**Issue by xiaoyafeng** [stsc/DateTime-Format-Natural#5]
what's one of the best on DT::F::N is that it provides a handy jump: last this next, 1st, 2nd etc  which I can set a people-read unit: day, week, month or may july, june etc. Recently my customer would like to request a new unit:  "quarter".
from my respective, quarter is just an alias of month：
  quarter1 is January; quarter2 is April quarter3 is July quarter4 is October
this quarter:   my $dt = DateTime->now;  $dt->clone->subtract(days, $dt->doq);
last quarter:   my $dt = DateTime->now;  $dt->clone->subtract(days, $dt->doq)->subtract(months, 3);
........
I could make another rewrite function to treat quarter before sending the string to DT::F::N,
but since quarter as a time unit is very popular and useful on financial area, I suggest you could consider  adding it on next version. Thanks.

**Comment by xiaoyafeng** [comment]
Wow! thanks for your prompt reply! I'm been so busy recently(life is always busy!;() that I can't perform full test on this. but I did some test manually and it runs as I want.
just 2 things:
1. it's my fault, this quarter should be $dt->subtract(days, $dt->doq -1)
2. As my first post, beside "quarter", quarter alias of January, April July and October is also required.
like:  last quarter1( means last January), this quarter4 (means this October ) etc.

**Comment by stsc** [comment]
1. No idea, I just trust you :-).
2. quarter1, quarter2, ... are barely "human-readable", so I'm reluctant to include it as is. If you can come up with something more sensible :-), i'm willing to consider it.

**Comment by stsc** [comment]
Made a release (`v1.06_01`) which partially addresses your wish(es). Let me know, if it works for you so far!

**Comment by xiaoyafeng** [comment]
It perfectly meet what I need, Thanks!

**Comment by stsc** [comment]
As for 2: can't "we" just use Q1, Q2, Q3 & Q4 instead (and ignore non-standard quarters, until the need to parse them arises? :-)

**Comment by stsc** [comment]
Closing. Feel free to raise another issue if desired.
