### ISSUE TITLE
Whishlist: more units for before and after

### ISSUE THREAD

**Issue by Sadrak** [stsc/DateTime-Format-Natural#6]
`1 hour before midnight` works as expected, but not `1 minute before midnight` or `1 second before midnight`.

Also `1 hour before yesterday` and `1 hour before tomorrow` works, but not `1 hour before today`.

And the same for `after`.

**Comment by stsc** [comment]
Uploaded `v1.07_01` which includes support for following new formats:

- 10 seconds before noon
- 10 minutes before noon
- 10 seconds before midnight
- 10 minutes before midnight
- 5 seconds after noon
- 5 minutes after noon
- 5 seconds after midnight
- 5 minutes after midnight

Will hopefully address the others shortly, thanks!

**Comment by Sadrak** [comment]
thanks, i am currently using "yesterday 23:59:59" that could be "1 second before today"

or would be some combos like "1 second before yesterday midnight" possible? (i don't need this, just ask for clarification).

Most of the time i use this to describe special times like "next hour".

**Comment by stsc** [comment]
Uploaded `v1.07_02` which includes support for following new formats:

- 6 hours before today
-  3 hours after today

Will hopefully address the others shortly, thanks!

**Comment by stsc** [comment]
Uploaded `v1.07_03` which includes support for following new formats:
- 6 seconds before yesterday
- 6 minutes before yesterday
- 6 seconds before today
- 6 minutes before today
- 6 seconds before tomorrow
- 6 minutes before tomorrow
- 3 seconds after yesterday
- 3 minutes after yesterday
- 3 seconds after today
- 3 minutes after today
- 3 seconds after tomorrow
- 3 minutes after tomorrow

**Comment by Sadrak** [comment]
Vielen Dank! :+1:
