### ISSUE TITLE
support common unit abbreviations

### ISSUE THREAD

**Issue by grr** [stsc/DateTime-Format-Natural#8]
(?:yr|hr|min|sec)s?

Edit: Looks like mins is partially supported: `10 mins` works but `1 min` doesn't.

**Comment by stsc** [comment]
This issue looks a bit more senseful to me. I agree that `1 min` should work if `10 mins` already does. I also agree that `sec(s)` should be supported.

I'm a bit undecided about the provided abbreviations for year/hour (?). It's up to you to convince me that they deserve to be added :-).

**Comment by grr** [comment]
facebook uses strings like "10 hrs" to indicate pubdate if less than a day old.

**Comment by stsc** [comment]
OK, I'm convinced (after some research :-).

Use subsequent patch against latest DateTime::Format::Natural (`v1.09`) and let me know, if it works for you! It's not complete yet, but I'm going to do it once you've confirmed it.

[dtfn.patch.txt](https://github.com/stsc/DateTime-Format-Natural/files/4792599/dtfn.patch.txt)

**Comment by grr** [comment]
works for me, thanks.

**Comment by stsc** [comment]
Would you like to be listed under [CREDITS](https://metacpan.org/pod/DateTime::Format::Natural#CREDITS)? If, please let me know your (real)name soonish!

**Comment by stsc** [comment]
Uploaded `v1.09_01` which includes support for your suggested formats!
